# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flareover < Formula
  desc "Deterministic Cloudflare → EU-sovereign migration engine (0% false positives)"
  homepage "https://www.flareover.com"
  version "0.2.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fabriziosalmi/flareover/releases/download/v0.2.0/flareover_0.2.0_darwin_amd64.tar.gz"
      sha256 "d1ed079671bf1ec689770e6ddbcf0b6aee2f8aa58d6d5ee38b3421b988cb0eaa"

      define_method(:install) do
        bin.install "flareover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fabriziosalmi/flareover/releases/download/v0.2.0/flareover_0.2.0_darwin_arm64.tar.gz"
      sha256 "69f362f165338153d689738ccb70fae19e034f8f603c3c8573ecda6cdcb1d21f"

      define_method(:install) do
        bin.install "flareover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabriziosalmi/flareover/releases/download/v0.2.0/flareover_0.2.0_linux_amd64.tar.gz"
      sha256 "9f960c9fd3f4ce1b44b2e811278cdc54ef9d124d482f89127bdfc8f44c4fd94d"
      define_method(:install) do
        bin.install "flareover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabriziosalmi/flareover/releases/download/v0.2.0/flareover_0.2.0_linux_arm64.tar.gz"
      sha256 "f5b6dd60b2ee2b9aa6dbce89bffb891ffdce11e26d2e8b379f47085ff31a7b4e"
      define_method(:install) do
        bin.install "flareover"
      end
    end
  end

  test do
    system "#{bin}/flareover", "version"
  end
end
