# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flareover < Formula
  desc "Deterministic Cloudflare → EU-sovereign migration engine (0% false positives)"
  homepage "https://www.flareover.com"
  version "0.1.7"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fabriziosalmi/flareover/releases/download/v0.1.7/flareover_0.1.7_darwin_amd64.tar.gz"
      sha256 "dece2deee7b323e28a6a7d6fae78ceff294dc2d11e2929946fd12101da374574"

      define_method(:install) do
        bin.install "flareover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fabriziosalmi/flareover/releases/download/v0.1.7/flareover_0.1.7_darwin_arm64.tar.gz"
      sha256 "b8d8d73bf11253455da03db7babb93ee59cd89ce4dfca7488e4a78b72de1cafb"

      define_method(:install) do
        bin.install "flareover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabriziosalmi/flareover/releases/download/v0.1.7/flareover_0.1.7_linux_amd64.tar.gz"
      sha256 "7b76c6d350e37388d1ca8415fc3031e286379f0b749483f1c9229fe41adff904"
      define_method(:install) do
        bin.install "flareover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabriziosalmi/flareover/releases/download/v0.1.7/flareover_0.1.7_linux_arm64.tar.gz"
      sha256 "b253c8f9d7eeaf9a36690b38fbc6de09125c29828570b00f5ef17627ce8bf421"
      define_method(:install) do
        bin.install "flareover"
      end
    end
  end

  test do
    system "#{bin}/flareover", "version"
  end
end
